//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class arabalar
    {
        public int aracno { get; set; }
        public string aracmarka { get; set; }
        public string aracmodel { get; set; }
        public string aracozellik { get; set; }
        public string aracbakimgunu { get; set; }
        public string arackm { get; set; }
        public decimal hgs { get; set; }
        public decimal gunluktutar { get; set; }
        public int bayino { get; set; }
    }
}
