//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arackiralamaContainer : DbContext
    {
        public arackiralamaContainer()
            : base("name=arackiralamaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<musteriler> musteriler1 { get; set; }
        public virtual DbSet<odemeler> odemeler1 { get; set; }
        public virtual DbSet<arabalar> arabalar1 { get; set; }
        public virtual DbSet<bayiler> bayiler1 { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar1 { get; set; }
    }
}
