//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class bayiler
    {
        public int bayino { get; set; }
        public string bayiadi { get; set; }
        public string bayiyetkilisi { get; set; }
        public string bayiadres { get; set; }
        public string bayitelefon { get; set; }
        public decimal bayiciro { get; set; }
    }
}
