//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public int musterino { get; set; }
        public string adsoyad { get; set; }
        public string telefon { get; set; }
        public string tckimlikno { get; set; }
        public string ehliyetdurumu { get; set; }
        public string adres { get; set; }
    }
}
