//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class odemeler
    {
        public int odemeno { get; set; }
        public decimal odemetutar { get; set; }
        public string odemetarih { get; set; }
        public decimal vadefarki { get; set; }
        public int musterino { get; set; }
        public int aracno { get; set; }
    }
}
